name: build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: version
        run: |
          uname -m
          docker version
  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: version
        run: |
          uname -m
          docker version

