name: oidc-test
on:
  workflow_dispatch:

env:
  AWS_REGION : "us-east-1"

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  oidc-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::791860731874:role/github-oidc
          aws-region: ${{ env.AWS_REGION }}
      - name: list-buckets
        run: |
          aws s3 ls


# jobs:
#   build-ubuntu:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4
#       - name: version
#         run: |
#           uname -m
#           docker version
#   build-mac:
#     runs-on: macos-latest

#     steps:
#       - uses: actions/checkout@v4
#       - name: version
#         run: |
#           uname -m
#           docker version

