
name: shared matrix
on:
  push:
  workflow_dispatch:

jobs:
  define-matrix:
    runs-on: ubuntu-22.04

    outputs:
      targets: ${{ steps.targets.outputs.targets }}
      layers: ${{ steps.layers.outputs.layers }}

    steps:
      - name: define targets
        id: targets
        run: |
          echo 'targets=["dev", "ci", "test", "sit"]' >> "$GITHUB_OUTPUT"
      - name: define layers
        id: layers
        run: |
          echo 'layers=["layer1", "layer2", "layer3"]' >> "$GITHUB_OUTPUT"

  terraform-plan:
    runs-on: ubuntu-22.04
    needs: define-matrix
    strategy:
      matrix:
        target: ${{ fromJSON(needs.define-matrix.outputs.targets) }}
        layer: ${{ fromJSON(needs.define-matrix.outputs.layers) }}

    steps:
      - name: terraform setup
        run: |
          terraform init
          terraform workspace select -or-create ${{ matrix.target }}
          terraform workspace list
      - name: terraform plan
        run: |
          echo "terraform plan"

  terraform-apply:
    runs-on: ubuntu-22.04
    needs:
    - define-matrix
    - terraform-plan
    environment:
      name: development
    strategy:
      matrix:
        target: ${{ fromJSON(needs.define-matrix.outputs.targets[0]) }}

    steps:
    - name: terraform apply
      run: |
        echo "terraform apply ${{ matrix.target}}"

