name: shared matrix
on:
  push:
  workflow_dispatch:

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      targets: ${{ steps.targets.outputs.targets }}

    steps:
      - name: define targets
        id: targets
        run: |
          echo 'targets=["dev", "ci", "test", "sit"]' >> "$GITHUB_OUTPUT"

  produce-artifacts:
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      matrix:
        targets: ${{ fromJSON(needs.define-matrix.outputs.targets) }}

    steps:
      - name: define target
        env:
          target: ${{ matrix.target }}
        run: |
          echo "$target" > target
      - name: produce artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: target

  consume-artifacts:
    runs-on: ubuntu-latest
    needs:
    - define-matrix
    - produce-artifacts
    strategy:
      matrix:
        color: ${{ fromJSON(needs.define-matrix.outputs.targets) }}

    steps:
    - name: retrieve artifact
      uses: actions/download-artifact@v5
      with:
        name: ${{ matrix.target }}

    - name: report target
      run: |
        cat target

