name: shared matrix
on:
  push:
  workflow_dispatch:

jobs:
  define-matrix:
    runs-on: ubuntu-22.04

    outputs:
      targets: ${{ steps.targets.outputs.targets }}

    steps:
      - name: define targets
        id: targets
        run: |
          echo 'targets=["dev", "ci", "test", "sit"]' >> "$GITHUB_OUTPUT"

  produce-artifacts:
    runs-on: ubuntu-22.04
    needs: define-matrix
    strategy:
      matrix:
        target: ${{ fromJSON(needs.define-matrix.outputs.targets) }}

    steps:
      - name: define target
        env:
          target: ${{ matrix.target }}
        run: |
          echo "$target" > target
      # - name: produce artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ matrix.target }}
      #     path: target
      - name: terraform setup
        run: |
          terraform init
          terraform workspace select -or-create $target
          terraform workspace list

  consume-artifacts:
    runs-on: ubuntu-22.04
    needs:
    - define-matrix
    - produce-artifacts
    strategy:
      matrix:
        target: ${{ fromJSON(needs.define-matrix.outputs.targets) }}

    steps:
    # - name: retrieve artifact
    #   uses: actions/download-artifact@v5
    #   with:
    #     name: ${{ matrix.target }}

    - name: report target
      run: |
        cat target
        echo $target


